### ISSUE TITLE
Missing requests dependency

### ISSUE THREAD

**Issue by manfredlift** [byrnereese/linkchecker-mkdocs#7]
Missing `requests` dependency:
https://github.com/byrnereese/linkchecker-mkdocs/blob/a75d765b0ec564e5ed0218880ed0b5ab4b973917/setup.cfg#L31-L32

When installing linkchecker in an isolated environment then it doesn't work
```bash
$ pipx install mkdocs-linkcheck
$ mkdocs-linkcheck
Traceback (most recent call last):
  File "/Users/mliiv/.local/bin/mkdocs-linkcheck", line 5, in <module>
    from mkdocs_linkcheck.__main__ import main
  File "/Users/mliiv/.local/pipx/venvs/mkdocs-linkcheck/lib/python3.9/site-packages/mkdocs_linkcheck/__init__.py", line 4, in <module>
    from .base import check_links, check_local, check_remotes
  File "/Users/mliiv/.local/pipx/venvs/mkdocs-linkcheck/lib/python3.9/site-packages/mkdocs_linkcheck/base.py", line 11, in <module>
    from .sync import check_urls as check_urls_sync
  File "/Users/mliiv/.local/pipx/venvs/mkdocs-linkcheck/lib/python3.9/site-packages/mkdocs_linkcheck/sync.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by YDX-2147483647** [comment]
I guess it's duplicate of #2.
